services:
  meijer-database:
    image: ghcr.io/baosystems/postgis:16-3.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - directus_database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
  meijer-cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    networks:
      - dokploy-network
  meijer-directus:
    build:
      context: .
    container_name: directus-meijer
    depends_on:
      meijer-database:
        condition: service_healthy
    ports:
      - 8055:8055
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
    networks:
      - dokploy-network
    env_file:
      - .env

volumes:
  directus_uploads:
  directus_extensions:
  directus_database: