services:
  meijer-directus:
    build:
      context: .
    container_name: directus-meijer
    ports:
      - 8055:8055
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
      - directus_database:/directus/database
    networks:
      - dokploy-network
    env_file:
      - .env

volumes:
  directus_uploads:
  directus_extensions:
  directus_database: