services:
  database:
    image: ghcr.io/baosystems/postgis:16-3.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  directus:
    build:
      context: .
    container_name: directus-meijer
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./schema-sync:/directus/schema-sync
    env_file:
      - .env
  mailhog:
    image: richarvey/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  postgres-data: