name: Build Docker images
 
on:
  push:
    branches: ["master"]
    paths:
      - "front-end/**"
      - ".github/workflows/**"
      
jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-24.04-arm
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          push: true
          # Make sure to replace with your own namespace and repository
          tags: |
            registery.codeit.website/meijertheorie-platform:latest
          platforms: linux/arm64
          build-args: |
            PUBLIC_DIRECTUS_URL=${{ secrets.PUBLIC_DIRECTUS_URL }}