name: Build and deploy

on:
  push:
    branches: ['master']
    paths:
      - 'front-end/**'
      - '.github/workflows/**'

jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          push: true
          # Make sure to replace with your own namespace and repository
          tags: |
            registery.codeit.website/meijertheorie-platform:latest
          platforms: linux/arm64
          build-args: |
            PUBLIC_DIRECTUS_URL=${{ secrets.PUBLIC_DIRECTUS_URL }} \
            EMAIL_FROM=${{ secrets.EMAIL_FROM }} \
            EMAIL_SMTP=${{ secrets.EMAIL_SMTP }} \
            EMAIL_SMTP_HOST=${{ secrets.EMAIL_SMTP_HOST }} \
            EMAIL_SMTP_PASSWORD=${{ secrets.EMAIL_SMTP_PASSWORD }} \
            EMAIL_SMTP_PORT=${{ secrets.EMAIL_SMTP_PORT }} \
            EMAIL_SMTP_USER=${{ secrets.EMAIL_SMTP_USER }} \
            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} \
            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}

      - name: Trigger Deployment
        run: |
          curl -X 'POST' \
          'https://deploy.codeit.website/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H 'Authorization: Bearer ${{ secrets.DOKPLOY_TOKEN }}' \
          -H 'Content-Type: application/json' \
          -d '{"json":{"applicationId": "Tr2ETnRjO4jaByxYSQ5Rz"}}'
